services:
  # --- BASES DE DATOS ---
  db-catalog:
    image: mysql:8.0
    container_name: db-catalog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_catalog_db
    ports:
      - "3306:3306"

  db-inventory:
    image: mysql:8.0
    container_name: db-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_inventory_db
    ports:
      - "3307:3306"

  db-auth:
    image: mysql:8.0
    container_name: db-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_auth_db
    ports:
      - "3308:3306"

  db-profile:
    image: mysql:8.0
    container_name: db-profile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_profile_db
    ports:
      - "3309:3306"

  db-cart:
    image: mysql:8.0
    container_name: db-cart
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_cart_db
    ports:
      - "3310:3306"

  # --- MICROSERVICIOS ---
  auth-service:
    build: ./auth_service
    container_name: auth-service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-auth:3306/nexus_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-auth

  catalog-service:
    build: ./catalog_service
    container_name: catalog-service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-catalog:3306/nexus_catalog_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-catalog

  inventory-service:
    build: ./inventory_service
    container_name: inventory-service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-inventory:3306/nexus_inventory_db
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-inventory
      - catalog-service



  profile-service:
    build: ./profile_service
    container_name: profile-service
    restart: on-failure
    ports: ["8083:8083"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-profile:3306/nexus_profile_db
      AUTH_SERVICE_URL: http://auth-service:8080
    depends_on: [db-profile, auth-service]




  cart-service:
    build: ./shopping_cart_service
    container_name: cart-service
    ports: ["8084:8084"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-cart:3306/nexus_cart_db
      AUTH_SERVICE_URL: http://auth-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8081
    depends_on: [db-cart, auth-service, catalog-service]