services:
  # --- BASES DE DATOS (Motores MySQL Independientes) ---
  db-catalog:
    image: mysql:8.0
    container_name: db-catalog
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_catalog_db
    ports:
      - "3306:3306"
    restart: always

  db-inventory:
    image: mysql:8.0
    container_name: db-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_inventory_db
    ports:
      - "3307:3306"
    restart: always

  db-auth:
    image: mysql:8.0
    container_name: db-auth
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_auth_db
    ports:
      - "3308:3306"
    restart: always

  db-profile:
    image: mysql:8.0
    container_name: db-profile
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_profile_db
    ports:
      - "3309:3306"
    restart: always

  db-cart:
    image: mysql:8.0
    container_name: db-cart
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_cart_db
    ports:
      - "3310:3306"
    restart: always

  db-order:
    image: mysql:8.0
    container_name: db-order
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_order_db
    ports:
      - "3311:3306"
    restart: always

  db-review:
    image: mysql:8.0
    container_name: db-review
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_review_db
    ports:
      - "3312:3306"
    restart: always

  db-wishlist:
    image: mysql:8.0
    container_name: db-wishlist
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_wishlist_db
    ports:
      - "3313:3306"
    restart: always

  db-category:
    image: mysql:8.0
    container_name: db-category
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_category_db
    ports: ["3314:3306"]
    restart: always

  db-payment:
    image: mysql:8.0
    container_name: db-payment
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nexus_payment_db
    ports: ["3315:3306"]
    restart: always

  # --- MICROSERVICIOS (Puertos 8080 al 8085) ---

  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-auth:3306/nexus_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-auth
    restart: on-failure

  catalog-service:
    build: ./catalog_service
    container_name: catalog-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-catalog:3306/nexus_catalog_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-catalog
    restart: on-failure

  inventory-service:
    build: ./inventory_service
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-inventory:3306/nexus_inventory_db
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-inventory
      - catalog-service
    restart: on-failure

  profile-service:
    build: ./profile_service
    container_name: profile-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-profile:3306/nexus_profile_db
      AUTH_SERVICE_URL: http://auth-service:8080
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-profile
      - auth-service
    restart: on-failure

  cart-service:
    build: ./shopping_cart_service
    container_name: cart-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-cart:3306/nexus_cart_db
      AUTH_SERVICE_URL: http://auth-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-cart
      - auth-service
      - catalog-service
    restart: on-failure

  order-service:
    build: ./order_service
    container_name: order-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-order:3306/nexus_order_db
      AUTH_SERVICE_URL: http://auth-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-order
      - auth-service
      - catalog-service
    restart: on-failure


  review-service:
    build: ./review_service
    container_name: review-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-review:3306/nexus_review_db
      AUTH_SERVICE_URL: http://auth-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-review
      - auth-service
      - catalog-service



  wishlist-service:
    build: ./wishlist_service
    container_name: wishlist-service
    ports: ["8087:8087"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-wishlist:3306/nexus_wishlist_db
      AUTH_SERVICE_URL: http://auth-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on: [db-wishlist, auth-service, catalog-service]



  category-service:
    build: ./category_service
    container_name: category-service
    ports: ["8088:8088"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-category:3306/nexus_category_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on: [db-category]



  payment-service:
    build: ./payment_service
    container_name: payment-service
    ports: ["8089:8089"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-payment:3306/nexus_payment_db
      ORDER_SERVICE_URL: http://order-service:8085
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db-payment
      - order-service