# Identificación del Servicio
spring.application.name=category-service
server.port=8088

# Configuración de Base de Datos (Puerto 3314 en el ecosistema Nexus)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway para migraciones automáticas
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Comunicación Feign (URL interna de Docker por defecto)
auth.service.url=${AUTH_SERVICE_URL:http://auth-service:8080}

# Registro de logs para depuración de Feign
logging.level.com.nexus.category_service.client=DEBUG