spring.application.name=category-service
server.port=8088

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3314/nexus_category_db?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=root123

spring.flyway.enabled=true