# Nombre del Microservicio
spring.application.name=inventory_service
server.port=8082

# Conexión a Base de Datos (Nexus Inventory)
# 'db-inventory' es el nombre del contenedor definido en docker-compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Migraciones Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Comunicación Feign (Hacia Catalog Service)
# Dentro de Docker usa el nombre del contenedor 'catalog-service'
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8081}

# Logs
logging.level.com.nexus=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG