spring.application.name=payment-service
server.port=8089

# Cambia el puerto local de respaldo al 3325
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
order.service.url=${ORDER_SERVICE_URL:http://localhost:8085} 