spring.application.name=payment-service
server.port=8089

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3315/nexus_payment_db?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=root123

spring.flyway.enabled=true
order.service.url=${ORDER_SERVICE_URL:http://localhost:8085}