spring.application.name=profile-service
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8080}