spring.application.name=wishlist-service
server.port=8087

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3313/nexus_wishlist_db?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=root123

spring.flyway.enabled=true
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8080}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8081}