spring.application.name=wishlist-service
server.port=8087

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8080}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8081}